// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgzrmBWRlK1jzaCv0QNd2-hL3swiWM5zo',
    appId: '1:830119339716:web:846a79bd9bfd5fec428b91',
    messagingSenderId: '830119339716',
    projectId: 'flutter-chat-app-857b1',
    authDomain: 'flutter-chat-app-857b1.firebaseapp.com',
    storageBucket: 'flutter-chat-app-857b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM85i79A2xfY8D3uh1gaGSx78pKxUQT9c',
    appId: '1:830119339716:android:423a3964a029e053428b91',
    messagingSenderId: '830119339716',
    projectId: 'flutter-chat-app-857b1',
    storageBucket: 'flutter-chat-app-857b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXUJ5SsfUWyWY9Olnn547gLi7dErHPh8g',
    appId: '1:830119339716:ios:ef206ce19cf4f8dd428b91',
    messagingSenderId: '830119339716',
    projectId: 'flutter-chat-app-857b1',
    storageBucket: 'flutter-chat-app-857b1.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
